# Generated by Django 6.0.7 on 2026-07-20 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdoEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'edo_establecimiento',
            },
        ),
        migrations.CreateModel(
            name='EdoRepEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'edo_rep_establecimiento',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'zona',
            },
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('colonia', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=10)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('edo_establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='establecimientos.edoestablecimiento')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='establecimientos.zona')),
            ],
            options={
                'db_table': 'establecimiento',
            },
        ),
        migrations.CreateModel(
            name='RepEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_pila', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('edo_rep_establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='establecimientos.edorepestablecimiento')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='establecimientos.establecimiento')),
            ],
            options={
                'db_table': 'rep_establecimiento',
            },
        ),
    ]
