# Generated by Django 4.2.30 on 2026-07-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutavisita',
            name='dia',
            field=models.CharField(default='Lunes', max_length=10),
        ),
    ]
