# Generated by Django 4.2.30 on 2026-07-25 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0001_initial'),
        ('rutas', '0002_rutavisita_dia'),
        ('entregas', '0002_alter_cargavehiculo_fecha_carga_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaEntregaOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='establecimientos.establecimiento')),
                ('ruta_entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rutas.rutaentrega')),
            ],
            options={
                'db_table': 'ruta_entrega_orden',
                'unique_together': {('ruta_entrega', 'establecimiento')},
            },
        ),
    ]
