# Generated by Django 4.2.30 on 2026-08-08 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('motivo', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'devolucion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EdoEmpleado',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'edo_empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EdoEntrega',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'edo_entrega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EdoPedido',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'edo_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EdoUsuario',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'edo_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('numero', models.IntegerField(db_column='numero', primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entrega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('numero', models.IntegerField(db_column='numero', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('calle', models.CharField(blank=True, db_column='estCalle', max_length=100, null=True)),
                ('numero_ext', models.CharField(blank=True, db_column='estNumero', max_length=20, null=True)),
                ('colonia', models.CharField(blank=True, db_column='estColonia', max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('entrega_id', models.IntegerField(blank=True, db_column='entrega', null=True)),
                ('rep_establecimiento_id', models.IntegerField(blank=True, db_column='rep_establecimiento', null=True)),
                ('edo_establecimiento_id', models.CharField(blank=True, db_column='edo_establecimiento', max_length=10, null=True)),
            ],
            options={
                'db_table': 'establecimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('numlicencia', models.CharField(max_length=20, unique=True)),
                ('vigencia', models.DateField()),
            ],
            options={
                'db_table': 'licencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('observaciones', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'movimientos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('num', models.IntegerField(db_column='num', primary_key=True, serialize=False)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateTimeField()),
                ('subtotal', models.DecimalField(blank=True, db_column='subtotal', decimal_places=2, max_digits=10, null=True)),
                ('iva', models.DecimalField(blank=True, db_column='iva', decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RutaEntrega',
            fields=[
                ('numero', models.IntegerField(db_column='numero', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('edo_ruta_entrega_id', models.CharField(blank=True, db_column='edo_ruta_entrega', max_length=10, null=True)),
            ],
            options={
                'db_table': 'ruta_entrega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoLicencia',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'tipo_licencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'tipo_movimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'tipo_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('numero', models.IntegerField(db_column='numero', primary_key=True, serialize=False)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateTimeField()),
                ('ruta_visita_id', models.IntegerField(blank=True, db_column='ruta_visita', null=True)),
                ('edo_visita_id', models.CharField(blank=True, db_column='edo_visita', max_length=10, null=True)),
            ],
            options={
                'db_table': 'visita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaReporteVentasAdmin',
            fields=[
                ('zona_id', models.IntegerField(primary_key=True, serialize=False)),
                ('zona_nombre', models.CharField(max_length=20)),
                ('periodo', models.CharField(blank=True, max_length=7, null=True)),
                ('total_pedidos', models.BigIntegerField()),
                ('total_subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True)),
                ('total_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True)),
                ('total_ventas', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True)),
                ('pedidos_entregados', models.BigIntegerField()),
                ('pedidos_cancelados', models.BigIntegerField()),
                ('vendedor', models.CharField(max_length=51)),
            ],
            options={
                'db_table': 'vta_reporte_ventas_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('num', models.IntegerField(db_column='num', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'zona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleMovimiento',
            fields=[
                ('cod_movimiento', models.ForeignKey(db_column='cod_movimientos', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='detalles', serialize=False, to='reportes.movimiento')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(db_column='precioUnitario', decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'detalle_movimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('num_pedido', models.ForeignKey(db_column='num_pedido', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='detalles', serialize=False, to='reportes.pedido')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(db_column='precioUnitario', decimal_places=2, max_digits=10)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'detalle_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntregaEstablecimiento',
            fields=[
                ('entrega', models.ForeignKey(db_column='entrega', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='paradas', serialize=False, to='reportes.entrega')),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('hora_entrega', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entrega_estable',
                'managed': False,
            },
        ),
    ]
