# Generated by Django 6.0.7 on 2026-07-20 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establecimientos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdoRutaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'edo_ruta_entrega',
            },
        ),
        migrations.CreateModel(
            name='EdoRutaVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'edo_ruta_visita',
            },
        ),
        migrations.CreateModel(
            name='RutaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('coordinador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_entrega_coordinador', to='usuarios.usuario')),
                ('edo_ruta_entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rutas.edorutaentrega')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_entrega_repartidor', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'ruta_entrega',
            },
        ),
        migrations.CreateModel(
            name='RutaVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('coordinador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_visita_coordinador', to='usuarios.usuario')),
                ('edo_ruta_visita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rutas.edorutavisita')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_visita_vendedor', to='usuarios.usuario')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='establecimientos.zona')),
            ],
            options={
                'db_table': 'ruta_visita',
            },
        ),
    ]
