# Generated by Django 6.0.7 on 2026-07-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('fecha_caducidad', models.DateField()),
                ('stock', models.IntegerField(default=0)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'producto',
            },
        ),
    ]
