# Generated by Django 6.0.7 on 2026-07-20 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establecimientos', '0001_initial'),
        ('rutas', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'edo_entrega',
            },
        ),
        migrations.CreateModel(
            name='EdoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'edo_vehiculo',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tipo_pago',
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tipo_vehiculo',
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('edo_entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entregas.edoentrega')),
                ('ruta_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rutas.rutaentrega')),
            ],
            options={
                'db_table': 'entrega',
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('motivo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entregas.entrega')),
            ],
            options={
                'db_table': 'devolucion',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('capacidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entregas.marca')),
            ],
            options={
                'db_table': 'modelo',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='establecimientos.establecimiento')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='visitas.pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
                ('tipo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entregas.tipopago')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_vin', models.CharField(max_length=100, unique=True)),
                ('placas', models.CharField(max_length=20, unique=True)),
                ('edo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entregas.edovehiculo')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entregas.modelo')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entregas.tipovehiculo')),
            ],
            options={
                'db_table': 'vehiculo',
            },
        ),
        migrations.AddField(
            model_name='entrega',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entregas.vehiculo'),
        ),
        migrations.CreateModel(
            name='CargaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entregas.vehiculo')),
            ],
            options={
                'db_table': 'carga_vehiculo',
            },
        ),
        migrations.CreateModel(
            name='EntregaEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField()),
                ('hora_entrega', models.TimeField()),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entregas.entrega')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='establecimientos.establecimiento')),
            ],
            options={
                'db_table': 'entrega_establecimiento',
                'unique_together': {('entrega', 'establecimiento')},
            },
        ),
    ]
