# Generated by Django 4.2.30 on 2026-07-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('entregas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargavehiculo',
            name='fecha_carga',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='cargavehiculo',
            unique_together={('usuario', 'vehiculo', 'fecha_carga')},
        ),
        migrations.AlterModelTable(
            name='cargavehiculo',
            table='emp_vehiculo',
        ),
    ]
